services:
  - type: web
    name: heal-smart-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://heal-smart-backend.onrender.com
      - key: REACT_APP_GOOGLE_CLIENT_ID
        value: 246049626035-uhst0uqgq7p7nt84f6idr1171nif77b8.apps.googleusercontent.com
      - key: REACT_APP_DID_API_KEY
        value: dmlqYXkuc2lydXZ1cnVAZ21haWwuY29t:aUJkCAVPU5wCXKLBHXjjY
      - key: REACT_APP_NURSE_AVATAR_URL
        value: https://raw.githubusercontent.com/did-developer-community/image-library/main/nurse1.jpg 